<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.console</groupId>
        <artifactId>console-parent</artifactId>
        <version>0.0.1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <version>0.0.1</version>
    <artifactId>console-core</artifactId>
    <packaging>jar</packaging>
    <description>
        console-core
    </description>

    <dependencies>
        <!-- SpringBoot Web -->
        <dependency>
            <groupId>com.console</groupId>
            <artifactId>console-framework</artifactId>
            <version>0.0.1</version>
        </dependency>
    </dependencies>
</project>