CREATE TABLE IF NOT EXISTS `s_payment_channel` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `channel_name` VARCHAR(64) NOT NULL,
  `icon` VARCHAR(255) DEFAULT NULL,
  `show_name` VARCHAR(64) NOT NULL,
  `sort` INT NOT NULL DEFAULT 0,
  `cur_type` VARCHAR(16) NOT NULL,
  `pay_status` TINYINT NOT NULL DEFAULT 0,
  `real_name_pay_status` TINYINT NOT NULL DEFAULT 0,
  `cash_out_status` TINYINT NOT NULL DEFAULT 0,
  `belong_class` VARCHAR(64) NOT NULL,
  `pay_type` VARCHAR(64) NOT NULL,
  `pay_url` VARCHAR(512) NOT NULL,
  `pay_call_back_url` VARCHAR(512) NOT NULL,
  `pay_search_url` VARCHAR(512) NOT NULL,
  `cash_out_url` VARCHAR(512) NOT NULL,
  `cash_out_call_back_url` VARCHAR(512) NOT NULL,
  `cash_out_search_url` VARCHAR(512) NOT NULL,
  `balance_query_url` VARCHAR(512) DEFAULT NULL,
  `app_key` VARCHAR(128) NOT NULL,
  `api_secret` VARCHAR(512) NOT NULL,
  `min_pay_amt` DECIMAL(18,2) DEFAULT NULL,
  `max_pay_amt` DECIMAL(18,2) DEFAULT NULL,
  `min_cash_out_amt` DECIMAL(18,2) DEFAULT NULL,
  `max_cash_out_amt` DECIMAL(18,2) DEFAULT NULL,
  `pay_fee_rate` DECIMAL(12,8) DEFAULT NULL,
  `cash_out_fee_rate` DECIMAL(12,8) DEFAULT NULL,
  `is_fixed_amt` TINYINT NOT NULL DEFAULT 0,
  `pay_amt_arr` VARCHAR(512) DEFAULT NULL,
  `white_ips` JSON DEFAULT NULL,
  `to_be_order_rate` DECIMAL(12,8) DEFAULT NULL,
  `remark` VARCHAR(512) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_payment_channel_status` (`pay_status`, `cash_out_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `s_payment_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_type` INT NOT NULL,
  `user_id` INT NOT NULL,
  `site_id` INT DEFAULT NULL,
  `team_id` INT DEFAULT NULL,
  `marketer_id` INT DEFAULT NULL,
  `payment_channel_id` BIGINT NOT NULL,
  `transaction_id` VARCHAR(128) DEFAULT NULL,
  `merchant_order_no` VARCHAR(64) DEFAULT NULL,
  `status` INT NOT NULL,
  `order_amt` DECIMAL(18,2) NOT NULL,
  `to_be_order_amt` DECIMAL(18,2) DEFAULT NULL,
  `fee` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `order_time` DATETIME(3) NOT NULL,
  `pay_url` TEXT DEFAULT NULL,
  `pay_time` DATETIME(3) DEFAULT NULL,
  `ip` VARCHAR(64) DEFAULT NULL,
  `advert_id` VARCHAR(128) DEFAULT NULL,
  `initiator_id` INT DEFAULT NULL,
  `operator_id` INT DEFAULT NULL,
  `operator_time` DATETIME(3) DEFAULT NULL,
  `recharge_times` INT NOT NULL DEFAULT 1,
  `error_msg` VARCHAR(1024) DEFAULT NULL,
  `complete_state` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_merchant_order` (`merchant_order_no`),
  UNIQUE KEY `uk_payment_channel_transaction` (`payment_channel_id`, `transaction_id`),
  KEY `idx_payment_user_time` (`user_id`, `order_time`),
  KEY `idx_payment_status` (`status`, `complete_state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `s_bank_card` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `card_code` VARCHAR(64) NOT NULL,
  `user_id` INT NOT NULL,
  `currency` VARCHAR(16) NOT NULL,
  `account_type` VARCHAR(32) NOT NULL,
  `bank_code` VARCHAR(64) DEFAULT NULL,
  `branch_bank_no` VARCHAR(64) DEFAULT NULL,
  `branch_bank_name` VARCHAR(128) DEFAULT NULL,
  `account_no` VARCHAR(255) NOT NULL,
  `account_name` VARCHAR(128) NOT NULL,
  `account_mobile` VARCHAR(64) DEFAULT NULL,
  `account_email` VARCHAR(128) DEFAULT NULL,
  `province` VARCHAR(128) DEFAULT NULL,
  `city` VARCHAR(128) DEFAULT NULL,
  `cpf` VARCHAR(32) DEFAULT NULL,
  `ifsc` VARCHAR(32) DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `create_time` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bank_card_code` (`card_code`),
  KEY `idx_bank_card_user` (`user_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `s_cash_out_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_type` INT NOT NULL,
  `wallet_type` INT NOT NULL,
  `bank_card_code` VARCHAR(64) NOT NULL,
  `user_id` INT NOT NULL,
  `market_site_id` INT DEFAULT NULL,
  `market_team_id` INT DEFAULT NULL,
  `marketer_id` INT DEFAULT NULL,
  `payment_channel_id` BIGINT NOT NULL,
  `transaction_id` VARCHAR(128) DEFAULT NULL,
  `merchant_order_no` VARCHAR(64) DEFAULT NULL,
  `status` INT NOT NULL,
  `order_amt` DECIMAL(18,2) NOT NULL,
  `fee` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `marketer_fee` DECIMAL(18,2) DEFAULT NULL,
  `surp_amt` DECIMAL(18,2) DEFAULT NULL,
  `initiator_id` INT DEFAULT NULL,
  `order_time` DATETIME(3) NOT NULL,
  `operator_id` INT DEFAULT NULL,
  `operator_time` DATETIME(3) DEFAULT NULL,
  `cash_out_time` DATETIME(3) DEFAULT NULL,
  `cash_out_count` INT NOT NULL DEFAULT 1,
  `complete_state` TINYINT NOT NULL DEFAULT 0,
  `remarks` VARCHAR(512) DEFAULT NULL,
  `error_msg` VARCHAR(1024) DEFAULT NULL,
  `error_type` INT DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cash_out_merchant_order` (`merchant_order_no`),
  UNIQUE KEY `uk_cash_out_channel_transaction` (`payment_channel_id`, `transaction_id`),
  KEY `idx_cash_out_user_time` (`user_id`, `order_time`),
  KEY `idx_cash_out_status` (`status`, `complete_state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
